# Generated by Django 4.0.4 on 2022-07-10 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('precio', models.IntegerField(verbose_name='$ ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Compra')),
                ('nombret', models.CharField(max_length=150, verbose_name='Nombre Tarjeta')),
                ('numerot', models.IntegerField(verbose_name='Numero Tarjeta')),
                ('fechat', models.DateField(verbose_name='Fecha Expericacion')),
                ('annot', models.IntegerField(verbose_name='Año')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
