# Generated by Django 4.0.4 on 2022-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0003_remove_compra_fechat_compra_mest_alter_compra_annot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numerot',
            field=models.IntegerField(verbose_name='Número Tarjeta'),
        ),
    ]
