# Generated by Django 4.0.4 on 2022-06-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
