# Generated by Django 4.0.4 on 2022-07-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suscripciones', '0002_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiposuscripcion', models.CharField(max_length=30, verbose_name='Suscripcion')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Compra')),
                ('nombret', models.CharField(max_length=150, verbose_name='Nombre Tarjeta')),
                ('numerot', models.IntegerField(verbose_name='Numero Tarjeta')),
                ('mest', models.IntegerField(verbose_name='Mes Exp')),
                ('annot', models.IntegerField(verbose_name='Año Exp')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
