# Generated by Django 4.0.4 on 2022-07-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_suscripcion_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=100000)),
                ('precio', models.IntegerField(verbose_name='$ ')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='tiposuscripcion',
        ),
    ]
