# Generated by Django 4.0.4 on 2022-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0004_tiposuscripcion_remove_suscripcion_tiposuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='numerot',
            field=models.IntegerField(verbose_name='Número Tarjeta'),
        ),
    ]
